/******************************************************************* 
 * Header file generated by Protoc for Embedded C.                 *
 * Version 0.2 (2012-01-31)                                        *
 *                                                                 *
 * Copyright (c) 2009-2012                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : Paladin.proto
 * Package: 
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/
#ifndef _OOOKK__
#define _OOOKK__

#define MAX_REPEATED_LEN 100
#define MAX_STRING_LEN 20
#define MAX_BYTES_LEN 32

/*******************************************************************
 * General functions
 *******************************************************************/

/*
 * returns the size of a length delimited message which also 
 * contains the first bytes for the length encoding.
 */
unsigned long Message_get_delimited_size(void *_buffer, int offset);

/*
 * Tests whether a message can be completely read from the given buffer at
 * the offset. The bytes [offset..offset+length-1] are interpreted.
 *
 * Returns 1 (true) if buffer[offset..offset+length-1] contains a complete
 * message or 0 (false) otherwise.
 */
int Message_can_read_delimited_from(void *_buffer, int offset, int length);


/*******************************************************************
 * Message: Paladin.proto, line 4
 *******************************************************************/

/* Maximum size of a serialized Heartbeat-message, useful for buffer allocation. */
#define MAX_Heartbeat_SIZE 5

/* Structure that holds a deserialized Heartbeat-message. */
struct Heartbeat {
  char _stat;
};
/*
 * Serialize a Heartbeat-message into the given buffer at offset and return
 * new offset for optional next message.
 */
int Heartbeat_write_delimited_to(struct Heartbeat *_Heartbeat, void *_buffer, int offset);

/*
 * Serialize a Heartbeat-message together with its tag into the given buffer 
 * at offset and return new offset for optional next message.
 * Is useful if a Heartbeat-message is embedded in another message.
 */
int Heartbeat_write_with_tag(struct Heartbeat *_Heartbeat, void *_buffer, int offset, int tag);

/*
 * Deserialize a Heartbeat-message from the given buffer at offset and return
 * new offset for optional next message.
 *
 * Note: All fields in _Heartbeat will be reset to 0 before _buffer is interpreted.
 */
int Heartbeat_read_delimited_from(void *_buffer, struct Heartbeat *_Heartbeat, int offset);
#endif
