// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Proto.proto

/*
Package Proto is a generated protocol buffer package.

It is generated from these files:
	Proto.proto

It has these top-level messages:
	ReqLogin
	RepLogin
*/
package Proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReqLogin struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Passwd string `protobuf:"bytes,2,opt,name=passwd" json:"passwd,omitempty"`
}

func (m *ReqLogin) Reset()                    { *m = ReqLogin{} }
func (m *ReqLogin) String() string            { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()               {}
func (*ReqLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ReqLogin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqLogin) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type RepLogin struct {
	Ret int32  `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *RepLogin) Reset()                    { *m = RepLogin{} }
func (m *RepLogin) String() string            { return proto.CompactTextString(m) }
func (*RepLogin) ProtoMessage()               {}
func (*RepLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RepLogin) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *RepLogin) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqLogin)(nil), "Proto.ReqLogin")
	proto.RegisterType((*RepLogin)(nil), "Proto.RepLogin")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for User service

type UserClient interface {
	Login(ctx context.Context, in *ReqLogin, opts ...grpc.CallOption) (*RepLogin, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) Login(ctx context.Context, in *ReqLogin, opts ...grpc.CallOption) (*RepLogin, error) {
	out := new(RepLogin)
	err := grpc.Invoke(ctx, "/Proto.User/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserServer interface {
	Login(context.Context, *ReqLogin) (*RepLogin, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqLogin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Proto.User/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Login(ctx, req.(*ReqLogin))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Proto.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _User_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Proto.proto",
}

func init() { proto.RegisterFile("Proto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2b, 0x00, 0x91, 0x42, 0xac, 0x60, 0x8e, 0x92, 0x19, 0x17, 0x47, 0x50, 0x6a, 0xa1,
	0x4f, 0x7e, 0x7a, 0x66, 0x9e, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02,
	0xa3, 0x06, 0x67, 0x10, 0x98, 0x2d, 0x24, 0xc6, 0xc5, 0x56, 0x90, 0x58, 0x5c, 0x5c, 0x9e, 0x22,
	0xc1, 0x04, 0x16, 0x85, 0xf2, 0x94, 0xf4, 0x40, 0xfa, 0x0a, 0x20, 0xfa, 0x04, 0xb8, 0x98, 0x8b,
	0x52, 0x4b, 0xc0, 0xda, 0x58, 0x83, 0x40, 0x4c, 0x90, 0x48, 0x6e, 0x71, 0x3a, 0x54, 0x0b, 0x88,
	0x69, 0x64, 0xcc, 0xc5, 0x12, 0x5a, 0x9c, 0x5a, 0x24, 0xa4, 0xcd, 0xc5, 0x0a, 0xd1, 0xc4, 0xaf,
	0x07, 0x71, 0x0d, 0xcc, 0x76, 0x29, 0x84, 0x00, 0xc4, 0x58, 0x25, 0x86, 0x24, 0x36, 0xb0, 0x53,
	0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x73, 0x33, 0xb4, 0xb9, 0x00, 0x00, 0x00,
}
