// Automatically generated by MockGen. DO NOT EDIT!
// Source: doer (interfaces: Doer)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Doer interface
type MockDoer struct {
	ctrl     *gomock.Controller
	recorder *_MockDoerRecorder
}

// Recorder for MockDoer (not exported)
type _MockDoerRecorder struct {
	mock *MockDoer
}

func NewMockDoer(ctrl *gomock.Controller) *MockDoer {
	mock := &MockDoer{ctrl: ctrl}
	mock.recorder = &_MockDoerRecorder{mock}
	return mock
}

func (_m *MockDoer) EXPECT() *_MockDoerRecorder {
	return _m.recorder
}

func (_m *MockDoer) DoSomething(_param0 int, _param1 string) error {
	ret := _m.ctrl.Call(_m, "DoSomething", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockDoerRecorder) DoSomething(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DoSomething", arg0, arg1)
}
